version: '2'

services:
  db : 
    # user: 37546:1001 # à utiliser uniquement sur le nas
    image: mongo
    restart: always 
    ports: 
    - 27017:27017
    volumes:
    - ./data:/data/db
    
  python_app: 
    build :
      context : .
      dockerfile : Dockerfile
    volumes: 
    - ./video:/work/video
    depends_on:
      - db
    
