version: '2'

services:
  db : 
    image: mongo
    restart: always 
    ports: 
    - 27017:27017
    
  python_app: 
    build :
      context : .
      dockerfile : Dockerfile
    depends_on:
      - db
